server:
  port: 8010


# 微信公众号Token
WX:
  TOKEN: PPFGR982JJKE1
# 微信公众号EncodingAESKey
  ENCODINGAESKEY: qmv3skFsMqlE2dTU1LTSsMMty12T4BFxNcu8IYV3BHn

# 淘宝联盟 APPKEY APPSECRET
TAOBAOLM:
  APPKEY: 29482829
  APPSECRET: 6131111a06246657fe676e855f341b69
  URL: http://gw.api.taobao.com/router/rest
